import "@/app/globals.css";


export const metadata = {
  title: "Pizzería",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (

    <html lang="es">
      <body className={`antialiased min-h-screen px-10`} >
            {children}
      </body>
    </html>
  
);
}
