import "@/app/globals.css";
import { Toaster } from "sonner";


export const metadata = {
  title: "Pizzería",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (

    <html lang="es">
      <body className={`antialiased min-h-screen p-10`} >
        {children}
        <Toaster position="top-right" richColors />
      </body>
    </html>

  );
}
